### ISSUE TITLE
Cannot Install

### ISSUE THREAD

**Issue by paranoidDBA** [microsoft/agdiag#2]
I'm trying to install this on Windows 11. When I run the setup.exe it says\:

![Image](https://github.com/user-attachments/assets/81c26769-8665-4443-9664-a904db05bf5d)

The Details button gives the text:

PLATFORM VERSION INFO
	Windows 			: 10.0.22631.0 (Win32NT)
	Common Language Runtime 	: 4.0.30319.42000
	System.Deployment.dll 		: 4.8.9176.0 built by: NET481REL1LAST_B
	clr.dll 			: 4.8.9282.0 built by: NET481REL1LAST_C
	dfdll.dll 			: 4.8.9176.0 built by: NET481REL1LAST_B
	dfshim.dll 			: 10.0.22621.1 (WinBuild.160101.0800)

SOURCES
	Deployment url			: file:///C:/agdiag/agdiag/agdiag/agdiag/agdiag.application
	Deployment Provider url		: file://dsdb/products/agdiag/current/agdiag.application

ERROR SUMMARY
	Below is a summary of the errors, details of these errors are listed later in the log.
	* Activation of C:\agdiag\agdiag\agdiag\agdiag\agdiag.application resulted in exception. Following failure messages were detected:
		+ Downloading file://dsdb/products/agdiag/current/agdiag.application did not succeed.
		+ The network path was not found.

		+ The network path was not found.

		+ The network path was not found.

COMPONENT STORE TRANSACTION FAILURE SUMMARY
	No transaction error was detected.

WARNINGS
	* The manifest for this application does not have a signature. Signature validation will be ignored.

OPERATION PROGRESS STATUS
	* [25/11/2024 11:18:26] : Activation of C:\agdiag\agdiag\agdiag\agdiag\agdiag.application has started.

ERROR DETAILS
	Following errors were detected during this operation.
	* [25/11/2024 11:18:32] System.Deployment.Application.DeploymentDownloadException (Unknown subtype)
		- Downloading file://dsdb/products/agdiag/current/agdiag.application did not succeed.
		- Source: System.Deployment
		- Stack trace:
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
			at System.Deployment.Application.SystemNetDownloader.DownloadAllFiles()
			at System.Deployment.Application.FileDownloader.Download(SubscriptionState subState, X509Certificate2 clientCertificate)
			at System.Deployment.Application.DownloadManager.DownloadManifestAsRawFile(Uri& sourceUri, String targetPath, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestDirect(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, IDownloadNotification notification, DownloadOptions options, ServerInformation& serverInformation)
			at System.Deployment.Application.DownloadManager.FollowDeploymentProviderUri(SubscriptionStore subStore, AssemblyManifest& deployment, Uri& sourceUri, TempFile& tempFile, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.DownloadManager.DownloadDeploymentManifestBypass(SubscriptionStore subStore, Uri& sourceUri, TempFile& tempFile, SubscriptionState& subState, IDownloadNotification notification, DownloadOptions options)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivation(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl, Uri& deploymentUri)
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
--- End of stack trace from previous location where exception was thrown ---
			at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
			at System.Deployment.Application.ApplicationActivator.PerformDeploymentActivationWithRetry(Uri activationUri, Boolean isShortcut, String textualSubId, String deploymentProviderUrlFromExtension, BrowserSettings browserSettings, String& errorPageUrl)
			at System.Deployment.Application.ApplicationActivator.ActivateDeploymentWorker(Object state)
		--- Inner Exception ---
		System.Net.WebException
		- The network path was not found.

		- Source: System
		- Stack trace:
			at System.Net.FileWebRequest.EndGetResponse(IAsyncResult asyncResult)
			at System.Deployment.Application.SystemNetDownloader.DownloadSingleFile(DownloadQueueItem next)
		--- Inner Exception ---
		System.Net.WebException
		- The network path was not found.

		- Source: System
		- Stack trace:
			at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)
			at System.Net.FileWebRequest.GetResponseCallback(Object state)
		--- Inner Exception ---
		System.IO.IOException
		- The network path was not found.

		- Source: mscorlib
		- Stack trace:
			at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
			at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
			at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy)
			at System.Net.FileWebStream..ctor(FileWebRequest request, String path, FileMode mode, FileAccess access, FileShare sharing, Int32 length, Boolean async)
			at System.Net.FileWebResponse..ctor(FileWebRequest request, Uri uri, FileAccess access, Boolean asyncHint)

COMPONENT STORE TRANSACTION DETAILS
	No transaction information is available.

**Comment by AndrewG2** [comment]
I had the same issue but was able to workaround it by changing line 11 in agdiag.application:
from:
<deploymentProvider codebase="file://dsdb/products/agdiag/current/agdiag.application" />
to the path containing the agdiag files:
<deploymentProvider codebase="file://C:/agdiag/current/agdiag.application" />

**Comment by paranoidDBA** [comment]
yes that works - thanks so much!
